spring:
  application:
    name: portfolio
  data:
    mongodb:
      host: localhost
      database: portfolio
  security:
    user:
      name: "admin"
      password: "pass"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "mail"
    password: "app password"
    properties:
      mail:
        smtp:
          auto: true
          starttls:
            enable: true
server:
  port: 8081

MYMAIL: "mail@gmail.com"


